### ISSUE TITLE
Fix issues from gl.kwarc.info

### ISSUE THREAD

**Issue by jfschaefer** [slatex/stexls#1]
We have moved the repository to github but the old issues should still be fixed:
[https://gl.kwarc.info/Marian6814/stexls/-/issues](https://gl.kwarc.info/Marian6814/stexls/-/issues)

**Comment by kohlhase** [comment]
These old issues amount for almost all the error messages I get from stexls nowadays. 
It would be great if they could be looked at.

**Comment by Mari6814** [comment]
Sorry, I don't understand what this means exactly?

**Comment by kohlhase** [comment]
das heißt, daß es toll wäre, wenn die alten issues gefixt würden (und nested modules), denn sie machen von den 500 remaining errors sicherlich 450 aus. Und ich kann die anderen nicht mehr finden, da sie unter diesen verschwinden. 

Hilft das?

**Comment by Mari6814** [comment]
Ich habe so viel wie möglich noch implementiert und gefixt.
Ich hoffe das Problem mit dem mhview und magma?magma war das Problem, das du implementiert haben wolltest.
Das sollte jetzt funktionieren.
