### ISSUE TITLE
do not report error "symbol undefined" when the module is not loaded. 

### ISSUE THREAD

**Issue by kohlhase** [slatex/stexls#11]
When I am missing an `\importmhmodule{foo}`, then on an instance of `\trefi[foo]{bar}`, stexls reports (something like) 
1. `symbol foo?bar of type \drefi... missing`
2. makes lots of suggestions 
3. and only in the end reports `symbol bar of type module is missing`. 

I often spend time reading and understanding the symbol stuff before I find the (only) relevant part at the end. 
It would be good if in the presence of 3., 1. and 2. could be left out. And while we are at it, it would be better to rephrase the error message from a user's point of view: something like 
```
\trefi[foo]{bar} invalid, since module "bar" is not imported here 
Add an appropriate "\importmhmodule", "\gimport", "\usemhmodule", or "\guse" somewhere. 
```

**Comment by Mari6814** [comment]
Fixed in new version.
