### ISSUE TITLE
tell stexls to ignore individual files? 

### ISSUE THREAD

**Issue by kohlhase** [slatex/stexls#12]
It would be good if I could tell stexls to ignore certain files (i.e. not report errors there). 
I am imgagining a file `.stexlsignore`, which has a set of regexps, and all files that match these are not considered when stexls reports problems. 
I know that I can systematically exclude things at the vscode level, but that is not what I want.

**Comment by kohlhase** [comment]
something that is also in the same direction, it seems that in the option ` "files.exclude": {.....` in `settings.json` should not be visited by stexls. 

I have the feeling that they are processed, generate error messages, but do not appear in the project overview, which is sub-optimal. 
It would be best, if the vscode plugin would provide these excluded files to exclude for the python stexls utility.

**Comment by Mari6814** [comment]
What should happen if you reference a file that is in one of these excluded lists?

For example in some file "smglom/example/source/example.tex" we add the line:
gimport[smglom/sets]{set}

This generates a reference to the file "smglom/sets/source/set.tex".
But what if you added "*/sets/*" to your exlude list?
Should the file "example.tex" still import "smglom/sets/source/set.tex" or should something
like a FileNotFound Diagnostic be risen and all the imported symbols be ignored?

**Comment by kohlhase** [comment]
hmmm, interesting. I guess that I imagined that this should not happen (except by accident). So that should raise an error, and not include (I do not really care what it does there).

**Comment by Mari6814** [comment]
Ignorefile is now live.
The file must be named ".stexlsignore" and must be in the same directory you opened with VSCode.

It uses a reduced gitignore file syntax:
One glob per line.
Each glob ignores the files it resolves to, or all files inside a directory if the glob resolves to a directory.
You can include files from ignored directories by prefixing the line with a "!".

Example:
```
a
!a/b
c/*/*.tex
d/**/*-suffix.tex
```

This ignorefile would ignore every file inside the directory "a",
except files inside directory "a/b".
Any \*.tex file inside a direct sub-directory of "c".
Any \*.tex file that ends with "-suffix" in its name and is located inside any directory of "d" (recursively).

**Comment by Mari6814** [comment]
I forgot to mention, that files that are somehow referenced are _not_ ignored. Implementing such a behaviour would take quite some time because a lot of places would need changing.
This ignorefile ignores files that would be compiled after starting the server.

**Comment by Mari6814** [comment]
While files that are referenced, are not ignored, they still do not generate lint diagnostics.

You can change the ignorefile at any time and it will take effect immediately.

**Comment by kohlhase** [comment]
> The file must be named ".stexlsignore" and must be in the same directory you opened with VSCode.

If I understand correctly, this file must be in the repository root? Or can it be in any directory and affect all files under this folder?

**Comment by Mari6814** [comment]
The `root` is the directory from which paths used in `\gimport` (or similar) environments are resolved.

For example `\gimport[smglom/sets]{set}` implies that the root directory is of the following structure:
```
root
├── .stexlsignore
├── MiKoMH
├──── ...
...
├── smglom
└──── sets
```

In VSCode you already added the `root` directory to your workspace using the `Open Folder...` command, else nothing would have resolved so far.

**Comment by kohlhase** [comment]
ah, thanks.

**Comment by kohlhase** [comment]
In essence it is a sister file to the `.stexls` file I guess.
