### ISSUE TITLE
file erraneously "not found"

### ISSUE THREAD

**Issue by kohlhase** [slatex/stexls#2]
In `.../MathHub/MiKoMH/AI/source/search/en/blackwhitebox.tex`, I get 
<img width="735" alt="Screenshot 2020-12-21 at 13 22 14" src="https://user-images.githubusercontent.com/4037538/102776752-9e4a8400-438f-11eb-93ff-cf01464666ff.png">
but the file exists. I have no idea what is happening. In particular, the LaTeX version finds the file.

**Comment by jfschaefer** [comment]
This was fixed in 1355918.
Reason was an uncaught exception during the compilation of the referenced file.
