### ISSUE TITLE
(old?) antlr dependency.

### ISSUE THREAD

**Issue by kohlhase** [slatex/stexls#4]
In my python environment and now `stexls` cannot find `antlr4`. 
@jfschaefer helped me work around this bug by downgrading antlr (I think). 
But now something has updated, and now I have the same problem again. The dependency in the python code should probably be updated.

**Comment by kohlhase** [comment]
It seems that `antlr4-python3-runtime` is installed on my system at version  4.8, which is what the web recommends.

**Comment by jfschaefer** [comment]
Closing for now, as it was a different problem.
Note that we had antlr versioning problems in the past, which may not have been resolved yet.
